const MULTIPLE_CHOICE = 'MULTIPLE_CHOICE';
const HEADING = 'HEADING';
const PARAGRAPH = 'PARAGRAPH';
const END = 'END';

export const SlideType = {
  MULTIPLE_CHOICE,
  HEADING,
  PARAGRAPH,
  END
};
